# -*- coding: utf-8 -*-
"""TASK 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFxUjfTU0_Ha7Qpg0Ru-wceOp0-gOBLw
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings('ignore')



data=pd.read_csv('/content/sample_data/titanic.csv')
pd.set_option('display.max_columns',None)
data.head()

data.describe()

data.info()

data.isna().sum()



"""HANDLING MISSING VALUES"""

data[data['Age'].isnull()]

data['Age'].median()

data['Age'].fillna(data['Age'].median(), inplace=True)
data

## FILING NULL VALUES IN EMBARKED USING MODE
data['Embarked'].mode()

data[data['Embarked'].isnull()]

data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True)

"""DROPPING CABIN COLUMN"""

# SINCE MAJORITY VALUES ARE MISSING DROPPING THE COLUMN
data.drop(columns=['Cabin'], inplace=True)
data

data.info()

data.head()

"""CHECKING FOR OUTLIERS"""

plt.figure(figsize=(10, 5))
sns.boxplot(data=data[['Age', 'Fare', 'SibSp', 'Parch']])  # Add relevant numeric columns
plt.title("Boxplot for Outlier Detection")
plt.show()

"""EDA"""

plt.figure(figsize=(10, 5))
sns.histplot(data['Age'], bins=30, kde=True)
plt.title("Age Distribution")
plt.show()

plt.figure(figsize=(10, 5))
sns.histplot(data['Fare'], bins=30, kde=True)
plt.title("Fare Distribution")
plt.show()

sns.countplot(x='Pclass', data=data, palette='coolwarm')
plt.title("Passenger Class Distribution")
plt.show()

## SURVIVAL RATE BY PASSENGER CLASS
sns.barplot(x="Pclass", y="Survived", data=data, palette="magma")
plt.title("Survival Rate by Passenger Class")
plt.show()

## SURVIVAL COUNT BY EMBARKATION PORT
sns.countplot(x='Embarked', hue='Survived', data=data, palette='Set1')
plt.title("Survival Count by Embarkation Port")
plt.show()

